### ISSUE TITLE
not working on QGIS-3.x

### ISSUE THREAD

**Issue by slaboor** [BergWerkGIS/QGIS-CKAN-Browser#18]
Hey, I love this plugin. Unfortunately it doesn't work on the newer QGIS versions anymore. Will this plugin be adapted to QGIS-3.x soon? That would be great!

Best regards
slaboor

**Comment by BergWerkGIS** [comment]
Thanks @slaboor 😄 

This project was sponsored and I haven't been able to raise more funding to update it to QGIS 3.x till now.
So, no timeline yet when an update will happen ☹️

**Comment by ryangarnett** [comment]
@BergWerkGIS do you have any ideas as to the funding that would be required? Or the timelines to complete? My organization is looking to do this work and we could be in a position to support.
Thanks....

**Comment by BergWerkGIS** [comment]
@ryangarnett that sounds great.

> do you have any ideas as to the funding that would be required? Or the timelines to complete?

I think update to 3.x itself shouldn't be too hard, maybe one or two days.

I would love to squeeze some other improvements (https://github.com/BergWerkGIS/QGIS-CKAN-Browser/issues) into an update as well.
But I don't have an estimate at hand for those, would have to familiarize myself with the topics again first.

> My organization is looking to do this work and we could be in a position to support.

Funding or coding the update?
Both are welcome.

**Comment by ryangarnett** [comment]
Hi Wilhelm,

Thank you for the speedy reply. I am glad to hear that you would be
interested in an update. I will look at the improvements that you are
interested in. As for the support, we would be willing to fund development,
would like to talk more about it if you are interested.

Thanks,
Ryan

**Comment by BergWerkGIS** [comment]
@ryangarnett perfect. Feel free to DM me: wb **_AT_** bergwerk-gis **_DOT_** at

**Comment by BergWerkGIS** [comment]
@slaboor I just uploaded a test version for QGIS 3.x
It's not yet in the offical plugins repository, but you can get it here
https://github.com/BergWerkGIS/QGIS-CKAN-Browser/releases
and install via `Plugins Manager -> Install from ZIP`.

It's a lot easier now to add your own CKAN instances.
It also pulls the list of CKAN Server from https://ckan.org/about/instances/
Unfortunately only a handful of them have an API URL defined so selection is not that big.

**Comment by slaboor** [comment]
Great! Thanks to all.
@BergWerkGIS I installed the Version v0.4-RC1.1 from ZIP successfully and I´m able to reach my CKAN Server and search for datasets. The only problem seems to be that apparently the cache directory path which has to be specified in the settings is not saved and so when I have selected a record to download I get the error message "Could not create cache directory: ...". Could you check that?

Thanks again!

**Comment by BergWerkGIS** [comment]
@slaboor thanks. I missed that. Will look into it latest tomorrow.

**Comment by BergWerkGIS** [comment]
@slaboor fixed.
Plugin update v0.3.94 (aka v0.4-RC2) is available via plugin manager.
Just check the experimental box to get it.

**Comment by slaboor** [comment]
@BergWerkGIS Thanks! I checked it already yesterday. For me everything is working fine now!

**Comment by dedenorio** [comment]
Hi @BergWerkGIS -- I have just installed QGIS 3.4 and CKAN crashes every time I try to download any data. I tried installing it from ZIP as well but the problem persists. And once it crashes I have to quit QGIS in order to try again. Any suggestions? Thanks!
![Screen Shot 2019-11-05 at 12 33 16 AM](https://user-images.githubusercontent.com/57077785/68181103-2a1f0800-ff64-11e9-95b2-5e91a651e38b.png)

**Comment by wilhelmberg** [comment]
@dedenorio the error looks like a connection problem.

To verify that the server hosting the requested resource actually works click on the dataset (1) and copy (2) the resource url into your browser:

![image](https://user-images.githubusercontent.com/4549888/68203866-16f15400-ffc7-11e9-9440-8c04474bc0b4.png)

If that doesn't work, then problem is caused by the server not being available or sending faulty data - although that shouldn't crash the plugin.

If it works then the problem lies within the plugin.
Enable debug logging (https://github.com/BergWerkGIS/QGIS-CKAN-Browser#settings) and copy and paste the messages from the log panel here.


If you share the CKAN Instance and the dataset you are trying to download I can have a look.

**Comment by dedenorio** [comment]
Thanks! :)

Yes -- one of the instances doesn't work when I paste the url to the browser, it times out (it's the City of Toronto).

For some in QGIS 3.x the CKAN window hides behind the canvas, which is why I would click on the CKAN icon and nothing would happen. I still have QGIS 2.10 installed and it's not a problem then.

Thanks!

**Comment by wilhelmberg** [comment]
@dedenorio 

I tested the two urls I found in the log files
```
http://dados.al.gov.br/api/3/
https://catalog.data.gov/api/3/
```
and downloaded a few datasets, but couldn't reproduce any errors.

> For some in QGIS 3.x the CKAN window hides behind the canvas, which is why I would click on the CKAN icon and nothing would happen.

That's weird and shouldn't happen.
My hunch is that this could be a Mac specific behavior.
Unfortunately I don't have a Mac for testing.
On Windows and Linux I haven't observed similar behavior.

Also, I didn't see any errors in the log files.

**Comment by dedenorio** [comment]
Thanks, I appreciate your trying it out.

Were you able to connect with the CIty of Toronto portal? This is the url I have tried -- I get a huge choice of datasets, but they time out in both QGIS and a browser:

https://ckan0.cf.opendata.inter.prod-toronto.ca/api/3/

Thanks!

**Comment by wilhelmberg** [comment]
@dedenorio yes, also getting an error with the Toronto portal.
Looks like wrong metadata being served by the API.

/cc @ryangarnett 

![image](https://user-images.githubusercontent.com/4549888/68249244-b130b680-001e-11ea-9ca6-a938d2bcea66.png)

**Comment by ryangarnett** [comment]
Thanks Willy. Best to direct that question to opendata@toronto.ca, which I
have cc'd on this email.

OD...can we look to see if there is an error with the CKAN API that would
be causing this issue.

Thanks,

Ryan

**Comment by ryangarnett** [comment]
Hi Willy

The issue is caused by our CKAN bug in resource URL. Our project team is working on a fix. New fix will release in early December.

Thanks
Gary Qi
Toronto Opendata Team
